# PortfolioCM
DO NOT SHOW THIS PORTFOLIO IN CLASS 

Introduction:
In my corpus I've chosen to compare two playlists that are matched to the specific song Station Atlantis. I released that song on Spotify last November. Many artist use the promotional tool of making a matching playlist to a song that they plan to release, and then add the song to the playlist, that by then ideally has gained some followers, on the release date. Spotify also makes playlists that are matched to a specific song called Radio's. This leaves us with two playlists: Café Atlatis, which was made by the person that wrote the song in question, and Radio Station Atlantis which was made by with the Spotify algorhithm. This ultimately can contribute to a number of fun questions, such as: does the A.I. know the artist better than (s)he knows him/herself? Does human intuition in playlist making differ from the choices that the algorhithm make in playlist making? These questions can ideally be explored with much more material; since making a playlist for your own song is a widespread promotional tool, there are many of these playlists to be found accross genres. 

One problem with this choice of corpus is that the Spotify Song Radio's are customized to your personal taste based on the listening history of your Spotify account. This creates a problem for my data because that already cause the material in Radio Station Atlantis to be closer to the material in Café Atlantis, as both are now adapted to my taste. My solution to this was to load a playlist from a new Spotify account (without a listening history). However, I would like to find a better solution to this eventually, or slightly alter the setup of my analysis. 

First Graph: 
In "Boxplot Atlantis" you can see Café Atlantis and Radio Atlantis (the algorhithm playlist) being compared on the parameters of valence (which describes the musical positiveness conveyed by the track, 1.00 being very positive and 0.00 very negative) and track popularity (how popular the individual tracks in the playlist are in general, meaning: not the amount of streams within the playlist, but also outside of it). I found it interesting to see that although the valence in both playlists is quite similar, the range of the track popularity is much wider in Café Atlantis that in Radio Atlantis. This might be because the algorhithm included the demographic that Station Atlantis came from a starting-out, unknown artist and therefore included other starting-out artists (perhaps also from the Netherlands particularly) in the Radio, whereas I as an artist included both my heroes (often very famous artists) and my friends (not very famous) in the playlist, causing a wide range. It seems as though the A.I. and me agree on the emotional quality of the playlist, but that I didn't look for equals in track popluarity whereas the A.I. did.  [BoxplotAtlantis](https://user-images.githubusercontent.com/97877741/220084125-0d5b9303-65c8-4200-a1a5-9eaf45b0ebb2.png)
 





